### ISSUE TITLE
Mingus 0.6: classes and mixins

### ISSUE THREAD

**Issue by edudobay** [edudobay/python-mingus#4]
Although @bspaans seems to have abandoned the project, I'd like to take it in the direction that he had intended to in this issue: https://github.com/bspaans/python-mingus/issues/23

**Comment by bspaans** [comment]
Hi @edudobay and happy new year. I've finally added you as a maintainer on both Github and PyPI so you should now be able to release a new python 3 version of Mingus. Have fun! :)

**Comment by edudobay** [comment]
Hi @bspaans and a happy new year :) Thanks, I shall be doing that soon!

**Comment by edudobay** [comment]
Closing this in favor of the original issue https://github.com/bspaans/python-mingus/issues/23
